"use client"

import { useState, useEffect, useRef } from "react"
import { Button } from "@/components/ui/button"
import { Card } from "@/components/ui/card"
import { ArrowLeft, Volume2, VolumeX, MapPin } from "lucide-react"

interface BenningtonTriangleProps {
  playerName: string
  onComplete: (subplotId: string, clue: string) => void
  onBack: () => void
  audioEnabled: boolean
  onToggleAudio: () => void
}

export default function BenningtonTriangle({
  playerName,
  onComplete,
  onBack,
  audioEnabled,
  onToggleAudio,
}: BenningtonTriangleProps) {
  const [currentScene, setCurrentScene] = useState("loading")
  const [displayedText, setDisplayedText] = useState("")
  const [isTyping, setIsTyping] = useState(false)
  const [showChoices, setShowChoices] = useState(false)
  const [loadingProgress, setLoadingProgress] = useState(0)
  const typewriterRef = useRef<NodeJS.Timeout>()

  const scenes = {
    loading: {
      title: "🌲 ACCESSING BENNINGTON TRIANGLE FILES",
      text: "Decrypting missing persons data...",
      choices: [],
    },
    intro: {
      title: "🌲 BENNINGTON TRIANGLE - MISSING PERSONS INVESTIGATION",
      text: `Agent ${playerName}, you've accessed the classified Bennington Triangle files. Between 1945 and 1950, five people vanished without a trace in this Vermont wilderness area. Official reports blame natural causes, but classified documents reveal something far more sinister: temporal displacement experiments. The missing persons weren't lost - they were displaced in time as test subjects for chronological manipulation technology. Electromagnetic anomalies in the area create "time pockets" where past, present, and future intersect. The experiments were designed to study how human consciousness responds to temporal displacement.`,
      choices: [
        { text: "Investigate the temporal anomalies", scene: "temporal" },
        { text: "Study the missing persons cases", scene: "missing" },
        { text: "Examine the displacement technology", scene: "technology" },
      ],
    },
    temporal: {
      title: "TEMPORAL DISPLACEMENT ANOMALIES",
      text: `Agent ${playerName}, the temporal anomalies in Bennington Triangle are artificially generated by hidden electromagnetic field generators buried throughout the forest. These devices create localized distortions in spacetime, allowing for controlled temporal displacement. The technology was developed from recovered artifacts of unknown origin. The anomalies don't just move people through time - they fragment their consciousness across multiple temporal states. Victims experience past, present, and future simultaneously, making them ideal test subjects for studying the nature of human consciousness and its relationship to linear time.`,
      choices: [
        { text: "Locate the field generators", scene: "generators" },
        { text: "Study consciousness fragmentation", scene: "fragmentation" },
        { text: "Investigate the artifact origins", scene: "artifacts" },
      ],
    },
    missing: {
      title: "MISSING PERSONS ANALYSIS",
      text: `Agent ${playerName}, the missing persons weren't random victims - they were carefully selected test subjects. Each had specific psychological profiles: high intelligence, strong sense of identity, and resistance to authority. The experiments aimed to determine if temporal displacement could be used to "edit" human consciousness by exposing subjects to alternate timelines where they made different choices. Some subjects were returned to the present with modified memories and personalities. Others remain displaced across time, their consciousness scattered across multiple temporal states.`,
      choices: [
        { text: "Track the returned subjects", scene: "returned" },
        { text: "Study consciousness editing", scene: "editing" },
        { text: "Investigate timeline manipulation", scene: "timeline" },
      ],
    },
    technology: {
      title: "TEMPORAL MANIPULATION TECHNOLOGY",
      text: `Agent ${playerName}, the displacement technology represents a breakthrough in temporal mechanics. The system can isolate individual consciousness from the timestream and move it to different temporal coordinates while keeping the body in the present. This creates a disconnect between mind and time, allowing researchers to study how consciousness perceives temporal information. The technology has been refined over decades and is now being deployed through digital devices. Every smartphone contains micro-displacement fields that create tiny temporal distortions in users' consciousness, making them more susceptible to manipulation.`,
      choices: [
        { text: "Study micro-displacement effects", scene: "micro" },
        { text: "Investigate digital deployment", scene: "digital" },
        { text: "Examine consciousness isolation", scene: "isolation" },
      ],
    },
    digital: {
      title: "DIGITAL TEMPORAL CONDITIONING",
      text: `Agent ${playerName}, the digital deployment of temporal displacement technology represents the final phase of consciousness control. Every digital device now contains micro-displacement fields that create tiny temporal distortions in users' consciousness. These distortions make people more susceptible to suggestion, less able to form long-term plans, and increasingly focused on immediate gratification. The technology fragments attention across multiple temporal states, creating a population that lives in a perpetual present with no real connection to past or future. This explains why people can't focus on long-term problems - their consciousness has been artificially fragmented.`,
      choices: [{ text: "Complete the investigation", scene: "complete" }],
    },
    complete: {
      title: "INVESTIGATION COMPLETE",
      text: `Agent ${playerName}, you've uncovered the truth about the Bennington Triangle. The missing persons were victims of temporal displacement experiments designed to study and control human consciousness. The technology developed here is now deployed globally through digital devices, creating a population with fragmented attention spans and diminished capacity for long-term thinking. The experiments in this remote Vermont forest were the prototype for a worldwide consciousness control system operating through temporal manipulation.`,
      choices: [{ text: "Return to main archives", scene: "return" }],
    },
    generators: {
      title: "ELECTROMAGNETIC FIELD GENERATORS",
      text: `Agent ${playerName}, the field generators are buried throughout the Bennington Triangle, creating a network of temporal distortion points. The devices are powered by unknown energy sources and appear to be self-maintaining. The generator network can create localized time pockets where different temporal states exist simultaneously. The technology is far beyond current human capabilities.`,
      choices: [{ text: "Complete the investigation", scene: "complete" }],
    },
    fragmentation: {
      title: "CONSCIOUSNESS FRAGMENTATION STUDY",
      text: `Agent ${playerName}, consciousness fragmentation occurs when human awareness is split across multiple temporal states. Subjects experience past, present, and future simultaneously, creating severe psychological trauma. The fragmentation makes subjects ideal for studying the nature of consciousness and its relationship to time. The research has led to breakthroughs in temporal manipulation technology.`,
      choices: [{ text: "Complete the investigation", scene: "complete" }],
    },
    artifacts: {
      title: "ARTIFACT ORIGIN INVESTIGATION",
      text: `Agent ${playerName}, the artifacts used to develop temporal displacement technology are of unknown origin. They appear to be remnants of an advanced civilization that existed long before recorded human history. The artifacts contain technology that manipulates the fundamental nature of spacetime. Similar artifacts have been found at other temporal anomaly sites worldwide.`,
      choices: [{ text: "Complete the investigation", scene: "complete" }],
    },
    returned: {
      title: "RETURNED SUBJECTS TRACKING",
      text: `Agent ${playerName}, subjects returned from temporal displacement show signs of consciousness modification. Their memories have been edited to remove traumatic experiences and implant false narratives. Many returned subjects become advocates for authority figures and show decreased resistance to manipulation. They serve as unwitting agents of the consciousness control program.`,
      choices: [{ text: "Complete the investigation", scene: "complete" }],
    },
    editing: {
      title: "CONSCIOUSNESS EDITING RESEARCH",
      text: `Agent ${playerName}, consciousness editing involves exposing subjects to alternate timelines where they made different choices. The process can modify personality traits, beliefs, and behavioral patterns by showing subjects "what could have been." The editing is so sophisticated that subjects believe the changes are natural personal growth rather than external manipulation.`,
      choices: [{ text: "Complete the investigation", scene: "complete" }],
    },
    timeline: {
      title: "TIMELINE MANIPULATION INVESTIGATION",
      text: `Agent ${playerName}, timeline manipulation allows researchers to test different versions of reality and select optimal outcomes. The technology can create alternate timelines where specific events unfold differently. The manipulation is used to guide human civilization toward predetermined goals by testing and implementing the most favorable timeline variations.`,
      choices: [{ text: "Complete the investigation", scene: "complete" }],
    },
    micro: {
      title: "MICRO-DISPLACEMENT EFFECTS",
      text: `Agent ${playerName}, micro-displacement effects create tiny temporal distortions in users' consciousness. The effects are subtle but cumulative, gradually fragmenting attention spans and reducing long-term thinking capabilities. Users become increasingly focused on immediate gratification and lose the ability to plan for the future. The effects explain the decline in human attention spans and critical thinking abilities.`,
      choices: [{ text: "Complete the investigation", scene: "complete" }],
    },
    isolation: {
      title: "CONSCIOUSNESS ISOLATION EXAMINATION",
      text: `Agent ${playerName}, consciousness isolation involves separating human awareness from the normal flow of time. Isolated consciousness can be studied, modified, and relocated to different temporal coordinates. The process allows researchers to understand the fundamental nature of human awareness and develop more sophisticated control mechanisms.`,
      choices: [{ text: "Complete the investigation", scene: "complete" }],
    },
  }

  const typewriterEffect = (text: string) => {
    setDisplayedText("")
    setIsTyping(true)
    setShowChoices(false)

    let index = 0
    const speed = 30

    const type = () => {
      if (index < text.length) {
        setDisplayedText(text.slice(0, index + 1))
        index++
        typewriterRef.current = setTimeout(type, speed)
      } else {
        setIsTyping(false)
        setShowChoices(true)
      }
    }

    type()
  }

  useEffect(() => {
    if (currentScene === "loading") {
      const loadingInterval = setInterval(() => {
        setLoadingProgress((prev) => {
          if (prev >= 100) {
            clearInterval(loadingInterval)
            setTimeout(() => setCurrentScene("intro"), 500)
            return 100
          }
          return prev + Math.random() * 8
        })
      }, 350)

      return () => clearInterval(loadingInterval)
    }
  }, [currentScene])

  useEffect(() => {
    const scene = scenes[currentScene as keyof typeof scenes]
    if (scene && currentScene !== "loading") {
      typewriterEffect(scene.text)
    }
  }, [currentScene])

  useEffect(() => {
    return () => {
      if (typewriterRef.current) {
        clearTimeout(typewriterRef.current)
      }
    }
  }, [])

  const handleChoice = (choice: any) => {
    if (!choice || !choice.scene) {
      console.error("Invalid choice:", choice)
      return
    }

    if (choice.scene === "complete") {
      setCurrentScene("complete")
    } else if (choice.scene === "return") {
      onComplete("bennington", "temporal_consciousness_fragmentation")
    } else if (scenes[choice.scene as keyof typeof scenes]) {
      setCurrentScene(choice.scene)
    } else {
      console.error("Scene not found:", choice.scene)
      setCurrentScene("intro")
    }
  }

  const scene = scenes[currentScene as keyof typeof scenes]

  // Add fallback for missing scenes
  if (!scene) {
    return (
      <div className="min-h-screen bg-black text-red-500 font-mono flex items-center justify-center p-4">
        <Card className="bg-black/90 border-red-500 border-2 p-6 max-w-md w-full shadow-2xl shadow-red-500/20">
          <div className="text-center space-y-4">
            <h2 className="text-xl font-bold text-red-500">🌲 TEMPORAL ANOMALY DETECTED</h2>
            <p className="text-red-400">Timeline disruption. Returning to main terminal...</p>
            <Button onClick={onBack} className="w-full bg-red-600 hover:bg-red-700 text-white min-h-[44px]">
              Return to Archives
            </Button>
          </div>
        </Card>
      </div>
    )
  }

  if (currentScene === "loading") {
    return (
      <div className="min-h-screen bg-black text-red-500 font-mono flex items-center justify-center p-4">
        <Card className="bg-black/90 border-red-500 border-2 p-6 max-w-md w-full shadow-2xl shadow-red-500/20">
          <div className="text-center space-y-4">
            <MapPin className="w-12 h-12 text-red-500 mx-auto animate-pulse" />
            <h2 className="text-xl font-bold text-red-500 terminal-glow">🌲 ACCESSING TRIANGLE FILES</h2>
            <div className="space-y-2">
              <p className="text-red-400 text-sm">Decrypting missing persons data...</p>
              <div className="w-full bg-gray-800 rounded-full h-2">
                <div
                  className="bg-red-500 h-2 rounded-full transition-all duration-300 animate-pulse"
                  style={{ width: `${loadingProgress}%` }}
                ></div>
              </div>
              <p className="text-xs text-gray-500">{Math.round(loadingProgress)}% Complete</p>
            </div>
            <div className="text-xs text-yellow-400 space-y-1">
              <p className="animate-pulse">🌲 LOCATION: REMOTE WILDERNESS</p>
              <p className="animate-pulse">⏰ TEMPORAL ANOMALIES: DETECTED</p>
            </div>
          </div>
        </Card>

        <style jsx>{`
          .terminal-glow {
            text-shadow: 0 0 10px #ff0000, 0 0 20px #ff0000;
          }
        `}</style>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-black text-red-500 font-mono p-4 relative overflow-hidden">
      <div className="absolute inset-0 opacity-5">
        <div className="absolute inset-0 bg-gradient-to-br from-green-900 via-black to-purple-900 animate-pulse"></div>
      </div>

      <div className="relative z-10 max-w-4xl mx-auto">
        <div className="flex justify-between items-center mb-6">
          <h1 className="text-lg sm:text-xl font-bold text-red-500 terminal-glow flex items-center">
            <MapPin className="w-5 h-5 mr-2" />
            {scene.title}
          </h1>
          <div className="flex gap-2">
            <Button
              onClick={onBack}
              variant="outline"
              size="sm"
              className="border-yellow-400 text-yellow-400 hover:bg-yellow-400 hover:text-black min-h-[44px]"
            >
              <ArrowLeft className="w-4 h-4" />
            </Button>
            <Button
              onClick={onToggleAudio}
              variant="outline"
              size="sm"
              className={`min-h-[44px] ${
                audioEnabled
                  ? "border-red-400 text-red-400 hover:bg-red-400"
                  : "border-gray-500 text-gray-400 hover:bg-gray-500"
              } hover:text-black`}
            >
              {audioEnabled ? <Volume2 className="w-4 h-4" /> : <VolumeX className="w-4 h-4" />}
            </Button>
          </div>
        </div>

        <Card className="bg-black/90 border-red-500 border-2 p-4 sm:p-6 mb-6 min-h-[400px] shadow-2xl shadow-red-500/20">
          <div className="text-red-300 leading-relaxed text-sm sm:text-base mb-6">
            {displayedText}
            {isTyping && <span className="animate-pulse text-red-500">█</span>}
          </div>

          {showChoices && scene.choices && scene.choices.length > 0 && (
            <div className="space-y-3">
              {scene.choices.map((choice, index) => (
                <Button
                  key={index}
                  onClick={() => handleChoice(choice)}
                  className="w-full text-left justify-start bg-red-900/20 border-red-500 text-red-400 hover:bg-red-900/40 hover:text-white p-4 h-auto min-h-[60px] transition-all duration-300"
                  variant="outline"
                >
                  <span className="text-red-600 mr-2">{">"}</span>
                  {choice.text}
                </Button>
              ))}
            </div>
          )}
        </Card>

        <div className="text-xs text-gray-500 text-center space-y-1">
          <p className="text-red-400">Location: Bennington Triangle | Temporal Status: UNSTABLE</p>
          <p className="animate-pulse">{">"} Missing persons: 5 | Timeline displacement: ACTIVE</p>
        </div>
      </div>

      <style jsx>{`
        .terminal-glow {
          text-shadow: 0 0 10px #ff0000;
        }
      `}</style>
    </div>
  )
}
